"""v2_workflows_triggers_credentials

Revision ID: 562afbed6c98
Revises: 
Create Date: 2026-02-24 12:19:52.406159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562afbed6c98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index('ix_cred_tenant_active', 'credentials', ['tenant_id', 'is_active'], unique=False)
    op.alter_column('mcp_servers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_cred_tenant_active', table_name='credentials')
    op.drop_column('credentials', 'is_active')
    # ### end Alembic commands ###
