"""{{project_name}} — NEXUS agent entry point.

Generated by `nexus init {{project_name}}`.
Run: nexus run "your task here"
"""

import asyncio
from nexus import Nexus


async def main():
    agent = Nexus(
        personas_yaml="personas.yaml",
        task_budget_usd=1.0,
    )

    result = await agent.run("{{first_task}}")

    print(f"Status:  {result['status']}")
    print(f"Seals:   {len(result.get('seals', []))}")
    if result.get("seals"):
        seal = result["seals"][-1]
        print(f"Last action: {seal['tool_name']} → {seal['status']}")


if __name__ == "__main__":
    asyncio.run(main())
